config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  devise_for :users
  resources :offers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :advertiser_name, presence: true
  validates :advertiser_name, uniqueness: true

  validates :url, presence: true
  validate :validate_url

  validates :description, presence: true
  validates :description, length: { 
    maximum: 500,
    too_long: "500 characters is the maximum allowed" 
  }

  validates :starts_at, presence: true

  def validate_url
    unless valid_url?
      errors.add(:url, "is not a valid HTTP URL")
    end
  end

  def valid_url?
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @offers = AvailableOffers.new.available_offers
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:edit, :update, :destroy]
  before_action :verify_admin!

  def index
    @offers = Offer.all.order(premium: :desc)
  end

  def new
    @offer = Offer.new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to(offers_path, notice: 'Offer was successfully created.') }
        format.json { render :index, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to(offers_path, notice: 'Offer was successfully updated.') }
        format.json { render :index, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def verify_admin!
    redirect_to root_path if current_user.nil? || !current_user.admin?
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium, :enable, :enable_admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% @offers.each do |offer| %>
  <div class="offer-card member">
    <b><%= offer.advertiser_name %></b>
    <p><%= offer.description %></p>

    <% if offer.premium %>
      <p class="premium">Premium</p>
    <% end %>

    <%= link_to 'Shop Now', offer.url, class: "shop input-bottom" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OffersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href=<%= root_path %>>Offers App</a>
      <div class="menu">
        <% if current_user %>
          <% if current_user.admin? %>
            <button class="btn btn-md btn-success">
              <%= link_to 'New Offer', new_offer_path %>
            </button>

            <%= link_to 'Manage Offers', offers_path, class: "btn btn-primary" %>
          <% end %>

          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>

          <%= link_to 'Sign in', new_user_session_path, class: "btn btn-success" %>
        <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<div class="div-form-offer">
  <%= form_with(model: offer, local: true) do |form| %>
    <% if offer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

        <ul>
          <% offer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :advertiser_name %>
      <%= form.text_field :advertiser_name %>
    </div>

    <div class="field">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :starts_at %>
      <%= form.date_select :starts_at %>
    </div>

    <div class="field">
      <%= form.label :ends_at %>
      <%= form.date_select :ends_at %>
    </div>

    <div class="field">
      <%= form.label :premium %>
      <%= form.check_box :premium %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-success'%>
    </div>
  <% end %>
</div>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

</br>
<button class="btn btn-primary"><%= link_to 'Back', offers_path %></button>

app/views/offers/index.html.erb
<br>

<% @offers.each do |offer| %>
  <div class="offer-card admin">
    <b><%= offer.advertiser_name %></b>
    <b><%= offer.url %></b>
    <p><%= offer.description %></p>
    <p>Starts: <%= offer.starts_at %></p>
    <p>Ends: <%= offer.ends_at %></p>
    <p>Offer <%= offer.enable ? 'Enable' : 'Disable' %></p>

    <% if offer.premium %>
      <p class="premium">Premium</p>
    <% end %>

    <div class="input-bottom">
      <%= form_for offer, method: :put do |f| %>
        <%= f.hidden_field :enable_admin, value: !offer.enable_admin %>
        <%= f.submit offer.enable_admin ? 'Enable' : 'Disable', 
          class: offer.enable_admin ? "btn btn-success" : "btn btn btn-danger" %>
      <% end %>

      <br>

      <div class="input-bottom ">
        <%= link_to 'Edit', edit_offer_path(offer), class: "btn btn-md btn-primary" %>
        <%= link_to 'Destroy', offer_path(offer),
            method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-md btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

</br>
<button class="btn btn-primary">
  <%= link_to 'Back', offers_path %>
</button>